services:
  airflow:
    image: apache/airflow:3.1.0
    command: >
      bash -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt && rm -f /opt/airflow/simple_auth_manager_passwords.json.generated && airflow standalone"
    environment:
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
      AIRFLOW_CONFIG: /opt/airflow/config/airflow.cfg
    depends_on:
      - otel-collector
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_home:/opt/airflow
      - ./airflow.cfg:/opt/airflow/config/airflow.cfg:ro
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"

volumes:
  airflow_home:
